# Generated by Django 5.2 on 2025-07-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customusermodel_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customusermodel",
            options={},
        ),
        migrations.RemoveField(
            model_name="customusermodel",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customusermodel",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="customusermodel",
            name="username",
        ),
    ]
