# Generated by Django 5.2 on 2025-07-26 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_customusermodel_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customusermodel",
            name="phone",
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="phone_number",
            field=models.CharField(
                default="a",
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^\\+989\\d{9}$")
                ],
            ),
            preserve_default=False,
        ),
    ]
