# Generated by Django 5.2 on 2025-07-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_customusermodel_phone_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customusermodel",
            old_name="phone_number",
            new_name="phone",
        ),
    ]
