# Generated by Django 5.2 on 2025-07-26 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_customusermodel_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
