# Generated by Django 5.2 on 2025-07-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_customusermodel_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
