# Generated by Django 5.2 on 2025-07-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_pendinguser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
