# Generated by Django 5.2 on 2025-06-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
