# Generated by Django 5.2 on 2025-06-26 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_comment_author_alter_comment_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date_create",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 27, 0, 44, 47, 696037)
            ),
        ),
    ]
