# Generated by Django 5.2 on 2025-06-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_comment_date_create"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_create",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
