# Generated by Django 5.2 on 2025-07-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_blog_author_alter_comment_author_delete_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="category",
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="blog_category", to="blog.category"
            ),
        ),
    ]
