# Generated by Django 5.2 on 2025-07-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_remove_blog_category_blog_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
    ]
