# Generated by Django 5.2 on 2025-07-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_remove_category_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="category",
            new_name="categories",
        ),
    ]
