# Generated by Django 5.2 on 2025-07-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_rename_category_blog_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="blog_category", to="blog.category"
            ),
        ),
    ]
